'use client';

/**
 * InvoiceGenerator — generates and downloads a PDF invoice for a completed transaction.
 * Uses jsPDF. Triggered by a button click.
 * Requirements: 10.1, 10.2
 */

import { useState } from 'react';

export interface InvoiceData {
  txId: string;
  sender: string;
  recipient: string;
  /** Human-readable amount string, e.g. "10.5" */
  amount: string;
  asset: string;
  /** ISO 8601 timestamp */
  timestamp: string;
  network: string;
}

interface InvoiceGeneratorProps {
  data: InvoiceData;
  /** Optional label override for the download button */
  label?: string;
}

export default function InvoiceGenerator({ data, label = 'Download Invoice' }: InvoiceGeneratorProps) {
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleDownload() {
    setGenerating(true);
    setError(null);
    try {
      // Use require instead of dynamic import to avoid chunking issues
      const jsPDF = (await import('jspdf')).jsPDF;

      const doc = new jsPDF({ unit: 'pt', format: 'a4' });
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 48;
      let y = 60;

      // Title
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text('Payment Invoice', margin, y);
      y += 32;

      // Divider
      doc.setDrawColor(200, 200, 200);
      doc.line(margin, y, pageWidth - margin, y);
      y += 20;

      // Fields
      const fields: [string, string][] = [
        ['Transaction ID', data.txId],
        ['Sender', data.sender],
        ['Recipient', data.recipient],
        ['Amount', `${data.amount} ${data.asset}`],
        ['Asset', data.asset],
        ['Timestamp', new Date(data.timestamp).toLocaleString()],
        ['Network', data.network],
      ];

      doc.setFontSize(11);
      for (const [label, value] of fields) {
        doc.setFont('helvetica', 'bold');
        doc.text(`${label}:`, margin, y);
        doc.setFont('helvetica', 'normal');
        // Wrap long values (e.g. tx IDs)
        const lines = doc.splitTextToSize(value, pageWidth - margin * 2 - 120);
        doc.text(lines, margin + 120, y);
        y += 18 * (Array.isArray(lines) ? lines.length : 1) + 4;
      }

      // Footer
      y += 20;
      doc.setFontSize(9);
      doc.setTextColor(150, 150, 150);
      doc.text('Generated by Stellar Freelance Platform', margin, y);

      const filename = `invoice-${data.txId.slice(0, 12)}.pdf`;
      doc.save(filename);
    } catch (err) {
      console.error('Invoice generation error:', err);
      setError(err instanceof Error ? err.message : 'Failed to generate invoice');
    } finally {
      setGenerating(false);
    }
  }

  return (
    <div className="flex flex-col gap-2">
      <button
        type="button"
        onClick={handleDownload}
        disabled={generating}
        className="inline-flex items-center gap-2 rounded-lg bg-gray-800 hover:bg-gray-900 dark:bg-gray-700 dark:hover:bg-gray-600 disabled:opacity-50 text-white text-sm font-medium px-4 py-2.5 transition-colors"
      >
        <DownloadIcon />
        {generating ? 'Generating…' : label}
      </button>
      {error && (
        <p role="alert" className="text-xs text-red-600 dark:text-red-400">
          {error}
        </p>
      )}
    </div>
  );
}

function DownloadIcon() {
  return (
    <svg
      className="h-4 w-4"
      viewBox="0 0 20 20"
      fill="currentColor"
      aria-hidden="true"
    >
      <path
        fillRule="evenodd"
        d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm3.293-7.707a1 1 0 011.414 0L9 10.586V3a1 1 0 112 0v7.586l1.293-1.293a1 1 0 111.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z"
        clipRule="evenodd"
      />
    </svg>
  );
}
